### ISSUE TITLE
about params

### ISSUE THREAD

**Issue by chaleeluo** [DeepGraphLearning/AStarNet#1]
good job! 
but I’m not sure in which case the propagation step param works and what if we introduce some multihop? 
(having some trouble with torchdrug -o-

**Comment by KiddoZhu** [comment]
Hi! Could you illustrate what you meant by "propagation step param"? For multi-hop, if you refer to complex logical queries, the current implementation A*Net doesn't support that.

**Comment by chaleeluo** [comment]
Oh, sure! I was trying to say the number of MLP layers, and I wonder the hidden layer might actually be more important than MLP layers? 

And yeah, it seems like multi-hop can't really exist in path-based reasoning.
Thanks!

**Comment by chaleeluo** [comment]
Hi, I'm quite confused 🤯 about this error, could you help me?

<img width="911" alt="image" src="https://github.com/DeepGraphLearning/AStarNet/assets/51904290/293f99a1-c84e-4abc-8037-2066f342bf4f">

**Comment by KiddoZhu** [comment]
Hi! Could you follow the solution here? https://github.com/DeepGraphLearning/NBFNet/issues/9, https://github.com/DeepGraphLearning/torchdrug/issues/89

I am trying to find a more robust solution for loading the checkpoints of A*Net.

**Comment by KiddoZhu** [comment]
Fixed in eec28db.

**Comment by chaleeluo** [comment]
Fantastic! but not enough, hh

<img width="1689" alt="image" src="https://github.com/DeepGraphLearning/AStarNet/assets/51904290/eb190a48-d158-4166-87a7-c090a6601e56">
