### ISSUE TITLE
AStarNet for link prediction task

### ISSUE THREAD

**Issue by boxorange** [DeepGraphLearning/AStarNet#2]
Hi,

Thanks for the great work! I'm actually using NBFNet, and I recently found this updated method. I'm trying to use AStarNet for a link prediction task as in NBFNet, but it looks like a link prediction task is not implemented in the current version. If possible, can you provide a guidance to use AStarNet for a link prediction task?

Many thanks in advance.

**Comment by KiddoZhu** [comment]
Hi! We only implement and test A\*Net on knowledge graph reasoning. We didn't know whether A\*Net will work for link prediction or not. Sorry.

**Comment by boxorange** [comment]
I see. Thanks for the reply.
